name: CI-Backend
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  compile:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: hostname

# Make sure you create gh secret to host the vault token
  get-sonar-passwrd:
    runs-on: self-hosted
    needs: [compile]
    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
            url: https://vault.expense.internal:8200
            token: ${{ secrets.VAULT_TOKEN }}
            tlsSkipVerify: true
            secrets: |
                infra-secrets/data/sonar password | sonar_password ;

  printing pwd:
    runs-on: self-hosted
    needs: [compile]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo $sonar_password

  static-code-analysis:
    runs-on: self-hosted
    needs: [compile]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: /sonar-scanner/sonar-scanner-6.2.1.4610-linux-x64/bin/sonar-scanner -Dsonar.host.url=http://sonar.expense.internal:9000 -Dsonar.projectKey=expense-backend -Dsonar.login=admin -Dsonar.password=${{ env.sonar_password }}

  security-checks-sast:
    runs-on: self-hosted
    needs: [compile]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  security-checks-sca:
    runs-on: self-hosted
    needs: [compile]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  unit-testing:
    runs-on: self-hosted
    needs: [security-checks-sca]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Unit Testing! - 'npm test'"

  integration-testing:
    runs-on: self-hosted
    needs: [security-checks-sca]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Integrations Testing! - 'npm verify'"
      
  build-docker-image:
    needs: [unit-testing,integration-testing]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  uploading-image:
    needs: [build-docker-image]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  dev-deployment:
    runs-on: self-hosted
    needs: [uploading-image]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  qa-deployment:
    runs-on: self-hosted
    needs: [dev-deployment]
    environment: qa
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  functional-testing:
    runs-on: self-hosted
    needs: [qa-deployment]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  endtoend-testing:
    needs: [qa-deployment]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  prod-deployment:
    needs: [endtoend-testing, functional-testing]
    runs-on: self-hosted
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

# Test Comment